[project]
name = "gorilla-bench-function-calling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.8.1",
    "torch>=2.7.1",
    "transformers>=4.53.0",
]
